-- Update admin password hash
-- Use the hash generated by PasswordHashGenerator.java

UPDATE users 
SET password_hash = '$2a$10$N9y.DBMErGifj9sevmFp7ui9G01/NrHK4mFfmZqQjM7xaSQNktNtq',
    is_locked = FALSE,
    locked_until = NULL,
    failed_login_attempts = 0
WHERE email = 'admin@volleyball.league';

-- Verify the update
SELECT 
    id,
    email,
    password_hash,
    first_name,
    last_name,
    is_active,
    is_locked,
    failed_login_attempts
FROM users 
WHERE email = 'admin@volleyball.league';


